//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouchPotato.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CouchPotato.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing episodes.
        /// </summary>
        public static string DatabaseImportEpisodes {
            get {
                return ResourceManager.GetString("DatabaseImportEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing genres.
        /// </summary>
        public static string DatabaseImportGenres {
            get {
                return ResourceManager.GetString("DatabaseImportGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing images.
        /// </summary>
        public static string DatabaseImportImages {
            get {
                return ResourceManager.GetString("DatabaseImportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing actors.
        /// </summary>
        public static string DatabaseImportPersons {
            get {
                return ResourceManager.GetString("DatabaseImportPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing roles.
        /// </summary>
        public static string DatabaseImportRoles {
            get {
                return ResourceManager.GetString("DatabaseImportRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing seasons.
        /// </summary>
        public static string DatabaseImportSeasons {
            get {
                return ResourceManager.GetString("DatabaseImportSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing videos.
        /// </summary>
        public static string DatabaseImportVideos {
            get {
                return ResourceManager.GetString("DatabaseImportVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database initialization.
        /// </summary>
        public static string DatabaseInitialization {
            get {
                return ResourceManager.GetString("DatabaseInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The migration has failed. The application will now close..
        /// </summary>
        public static string DatabaseMigrationFailed {
            get {
                return ResourceManager.GetString("DatabaseMigrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Migration service not found.
        /// </summary>
        public static string DatabaseMigrationServiceNotFound {
            get {
                return ResourceManager.GetString("DatabaseMigrationServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving database.
        /// </summary>
        public static string DatabaseSaving {
            get {
                return ResourceManager.GetString("DatabaseSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updating database.
        /// </summary>
        public static string DatabaseUpdating {
            get {
                return ResourceManager.GetString("DatabaseUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the folder containing Videlib images.
        /// </summary>
        public static string FileSystemSelectVidelibImageFolder {
            get {
                return ResourceManager.GetString("FileSystemSelectVidelibImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string VideoExplorerSearchHint {
            get {
                return ResourceManager.GetString("VideoExplorerSearchHint", resourceCulture);
            }
        }
    }
}
